CREATE DATABASE SoftUni
USE SoftUni

CREATE TABLE Towns
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(15) NOT NULL
)

CREATE TABLE Addresses 
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
AddressText VARCHAR(MAX),
TownId INT
)

CREATE TABLE Departments 
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE Employees 
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(15) NOT NULL,
MiddleName VARCHAR(15),
LastName VARCHAR(15) NOT NULL,
JobTitle VARCHAR(20),
DepartmentId VARCHAR(35),
HireDate DATE,
Salary DECIMAL(8,2),
AddressId INT
)